#
# Goldiriath v0.0.1 pre-alpha configuration
#

# Sign based mob spawner
mobspawner:
    enabled: true

    # Development mode
    # When this is set to true, all mobspawns will be disabled and presented as signs.
    dev_mode: true

    # Radius for mob spawners
    radius: 20

    # Maximum amount of mobs in the spawner radius
    max_mobs: 5

    # Minimum delay after a spawn in ticks
    # 400 ticks = 20 * 20 ticks = 20 seconds
    spawn_threshold: 400

# If enabled, dispensers will never run out
infinite_dispenser:
    enabled: true

