name: Goldiriath
version: 0.0.1
main: me.dirkjan.goldiriath.Goldiriath
commands:
    goldiriath:
        usage: /<command> [reload]
        aliases: [go]
        description: Shows information about the Goldiriath plugin.
    mobspawn:
        usage: /<command> dev <on | off>
        description: Manages mobspawns.
        aliases: [ms,mobmanage]