
hellzombie:
    name: '&4Zombie of Hell'
    type: ZOMBIE
    level: 5
    spawn_threshold: 6000
    item: IRON_SWORD:5
    helmet: LEATHER_HELMET:3
    chestplate: DIAMOND_CHESTPLATE:2
    leggings: GOLD_LEGGINGS
    boots: IRON_BOOTS:15